OGRE: Ogre::CPreprocessor::Token Class Reference
Ogre::CPreprocessor::Token Class Reference
A input token.
Public Types
enum Kind {
TK_EOS, TK_ERROR, TK_WHITESPACE, TK_NEWLINE,
TK_LINECONT, TK_NUMBER, TK_KEYWORD, TK_PUNCTUATION,
TK_DIRECTIVE, TK_STRING, TK_COMMENT, TK_LINECOMMENT,
TK_TEXT, TK_EOS, TK_ERROR, TK_WHITESPACE,
TK_NEWLINE, TK_LINECONT, TK_NUMBER, TK_KEYWORD,
TK_PUNCTUATION, TK_DIRECTIVE, TK_STRING, TK_COMMENT,
TK_LINECOMMENT, TK_TEXT
}
enum Kind {
TK_EOS, TK_ERROR, TK_WHITESPACE, TK_NEWLINE,
TK_LINECONT, TK_NUMBER, TK_KEYWORD, TK_PUNCTUATION,
TK_DIRECTIVE, TK_STRING, TK_COMMENT, TK_LINECOMMENT,
TK_TEXT, TK_EOS, TK_ERROR, TK_WHITESPACE,
TK_NEWLINE, TK_LINECONT, TK_NUMBER, TK_KEYWORD,
TK_PUNCTUATION, TK_DIRECTIVE, TK_STRING, TK_COMMENT,
TK_LINECOMMENT, TK_TEXT
}
Public Member Functions
Token ()
Token ()
Token (Kind iType)
Token (Kind iType)
Token (Kind iType, const char *iString, size_t iLength)
Token (Kind iType, const char *iString, size_t iLength)
Token (const Token &iOther)
Token (const Token &iOther)
~Token ()
~Token ()
void Append (const char *iString, size_t iLength)
Append a string to this token.
void Append (const char *iString, size_t iLength)
Append a string to this token.
void Append (const Token &iOther)
Append a token to this token.
void Append (const Token &iOther)
Append a token to this token.
void AppendNL (int iCount)
Append given number of newlines to this token.
void AppendNL (int iCount)
Append given number of newlines to this token.
int CountNL ()
Count number of newlines in this token.
int CountNL ()
Count number of newlines in this token.
bool GetValue (long &oValue) const
Get the numeric value of the token.
bool GetValue (long &oValue) const
Get the numeric value of the token.
Token & operator= (const Token &iOther)
Assignment operator.
Token & operator= (const Token &iOther)
Assignment operator.
bool operator== (const Token &iOther)
Test two tokens for equality.
bool operator== (const Token &iOther)
Test two tokens for equality.
void SetValue (long iValue)
Set the numeric value of the token.
void SetValue (long iValue)
Set the numeric value of the token.
Public Attributes
union {
char * Buffer
A memory-allocated string.
const char * String
A pointer somewhere into the input buffer.
};
union {
char * Buffer
A memory-allocated string.
const char * String
A pointer somewhere into the input buffer.
};
size_t Allocated
True if string was allocated (and must be freed)
size_t Length
Token length in bytes.
Kind Type
Token type.
Detailed Description
A input token.
For performance reasons most tokens will point to portions of the input stream, so no unneeded memory allocation is done. However, in some cases we must allocate different memory for token storage, in this case this is signalled by setting the Allocated member to non-zero in which case the destructor will know that it must free memory on object destruction.
Again for performance reasons we use malloc/realloc/free here because C++-style new[] lacks the realloc() counterpart.
Member Enumeration Documentation
enum Ogre::CPreprocessor::Token::Kind
Enumerator
TK_EOS
TK_ERROR
TK_WHITESPACE
TK_NEWLINE
TK_LINECONT
TK_NUMBER
TK_KEYWORD
TK_PUNCTUATION
TK_DIRECTIVE
TK_STRING
TK_COMMENT
TK_LINECOMMENT
TK_TEXT
TK_EOS
TK_ERROR
TK_WHITESPACE
TK_NEWLINE
TK_LINECONT
TK_NUMBER
TK_KEYWORD
TK_PUNCTUATION
TK_DIRECTIVE
TK_STRING
TK_COMMENT
TK_LINECOMMENT
TK_TEXT
enum Ogre::CPreprocessor::Token::Kind
Enumerator
TK_EOS
TK_ERROR
TK_WHITESPACE
TK_NEWLINE
TK_LINECONT
TK_NUMBER
TK_KEYWORD
TK_PUNCTUATION
TK_DIRECTIVE
TK_STRING
TK_COMMENT
TK_LINECOMMENT
TK_TEXT
TK_EOS
TK_ERROR
TK_WHITESPACE
TK_NEWLINE
TK_LINECONT
TK_NUMBER
TK_KEYWORD
TK_PUNCTUATION
TK_DIRECTIVE
TK_STRING
TK_COMMENT
TK_LINECOMMENT
TK_TEXT
Constructor & Destructor Documentation
Ogre::CPreprocessor::Token::Token () inline
Referenced by operator==().
Ogre::CPreprocessor::Token::Token (Kind iType) inline
Ogre::CPreprocessor::Token::Token (Kind iType, const char * iString, size_t iLength) inline
Ogre::CPreprocessor::Token::Token (const Token & iOther) inline
References Allocated, Length, String, and Type.
Ogre::CPreprocessor::Token::~Token () inline
References Buffer.
Ogre::CPreprocessor::Token::Token () inline
Ogre::CPreprocessor::Token::Token (Kind iType) inline
Ogre::CPreprocessor::Token::Token (Kind iType, const char * iString, size_t iLength) inline
Ogre::CPreprocessor::Token::Token (const Token & iOther) inline
Ogre::CPreprocessor::Token::~Token () inline
References Buffer.
Member Function Documentation
void Ogre::CPreprocessor::Token::Append (const char * iString, size_t iLength)
Append a string to this token.
Referenced by operator=().
void Ogre::CPreprocessor::Token::Append (const char * iString, size_t iLength)
Append a string to this token.
void Ogre::CPreprocessor::Token::Append (const Token & iOther)
Append a token to this token.
void Ogre::CPreprocessor::Token::Append (const Token & iOther)
Append a token to this token.
void Ogre::CPreprocessor::Token::AppendNL (int iCount)
Append given number of newlines to this token.
Referenced by operator=().
void Ogre::CPreprocessor::Token::AppendNL (int iCount)
Append given number of newlines to this token.
int Ogre::CPreprocessor::Token::CountNL ()
Count number of newlines in this token.
Referenced by operator=().
int Ogre::CPreprocessor::Token::CountNL ()
Count number of newlines in this token.
bool Ogre::CPreprocessor::Token::GetValue (long & oValue) const
Get the numeric value of the token.
Referenced by operator=(), and Ogre::CPreprocessor::Macro::~Macro().
bool Ogre::CPreprocessor::Token::GetValue (long & oValue) const
Get the numeric value of the token.
Token& Ogre::CPreprocessor::Token::operator= (const Token & iOther) inline
Assignment operator.
References Allocated, Append(), AppendNL(), Buffer, CountNL(), GetValue(), Length, SetValue(), String, and Type.
Token& Ogre::CPreprocessor::Token::operator= (const Token & iOther) inline
Assignment operator.
References Append(), AppendNL(), Buffer, CountNL(), GetValue(), and SetValue().
bool Ogre::CPreprocessor::Token::operator== (const Token & iOther) inline
Test two tokens for equality.
References Token().
bool Ogre::CPreprocessor::Token::operator== (const Token & iOther) inline
Test two tokens for equality.
References Length, and String.
void Ogre::CPreprocessor::Token::SetValue (long iValue)
Set the numeric value of the token.
Referenced by operator=().
void Ogre::CPreprocessor::Token::SetValue (long iValue)
Set the numeric value of the token.
Member Data Documentation
union { ... }
union { ... }
size_t Ogre::CPreprocessor::Token::Allocated mutable
True if string was allocated (and must be freed)
Referenced by operator=(), and Token().
char* Ogre::CPreprocessor::Token::Buffer
A memory-allocated string.
Referenced by operator=(), and ~Token().
size_t Ogre::CPreprocessor::Token::Length
Token length in bytes.
Referenced by operator=(), operator==(), and Token().
const char* Ogre::CPreprocessor::Token::String
A pointer somewhere into the input buffer.
Referenced by operator=(), operator==(), and Token().
Kind Ogre::CPreprocessor::Token::Type
Token type.
Referenced by operator=(), and Token().
The documentation for this class was generated from the following files:
Plus/include/GLSL/OgreGLSLPreprocessor.h
OgreGLSLESPreprocessor.h