OGRE: Ogre::OSXGL3PlusSupport Class Reference
Ogre::OSXGL3PlusSupport Class Reference
#include <OgreOSXGLSupport.h>
Public Types
enum ContextProfile { CONTEXT_CORE = 1, CONTEXT_COMPATIBILITY = 2, CONTEXT_ES = 4 }
typedef set< String >::type ExtensionList
Public Member Functions
OSXGL3PlusSupport (int profile)
~OSXGL3PlusSupport ()
void addConfig (void)
Add any special config values to the system.
bool checkExtension (const String &ext) const
virtual GLPBuffer * createPBuffer (PixelComponentType format, size_t width, size_t height)
RenderWindow * createWindow (bool autoCreateWindow, RenderSystem *renderSystem, const String &windowTitle)
ConfigOptionMap & getConfigOptions ()
virtual unsigned int getDisplayMonitorCount () const
Gets the number of display monitors.
void * getProcAddress (const char *name)
Get the address of a function.
virtual RenderWindow * newWindow (const String &name, unsigned int width, unsigned int height, bool fullScreen, const NameValuePairList *miscParams=0)
virtual void setConfigOption (const String &name, const String &value)
void start ()
Start anything special.
void stop ()
Stop anything special.
String validateConfig (void)
Make sure all the extra options are valid.
Static Public Member Functions
static CFComparisonResult _compareModes (const void *val1, const void *val2, void *context)
static Boolean _getDictionaryBoolean (CFDictionaryRef dict, const void *key)
static long _getDictionaryLong (CFDictionaryRef dict, const void *key)
Protected Attributes
ExtensionList extensionList
ContextProfile mContextProfile
ConfigOptionMap mOptions
Member Typedef Documentation
typedef set<String>::type Ogre::GLNativeSupport::ExtensionList inherited
Member Enumeration Documentation
enum Ogre::GLNativeSupport::ContextProfile inherited
Enumerator
CONTEXT_CORE
CONTEXT_COMPATIBILITY
CONTEXT_ES
Constructor & Destructor Documentation
Ogre::OSXGL3PlusSupport::OSXGL3PlusSupport (int profile) inline
Ogre::OSXGL3PlusSupport::~OSXGL3PlusSupport () inline
References _compareModes(), _getDictionaryBoolean(), _getDictionaryLong(), addConfig(), createWindow(), getProcAddress(), newWindow(), start(), stop(), and validateConfig().
Member Function Documentation
static CFComparisonResult Ogre::OSXGL3PlusSupport::_compareModes (const void * val1, const void * val2, void * context) static
Referenced by ~OSXGL3PlusSupport().
static Boolean Ogre::OSXGL3PlusSupport::_getDictionaryBoolean (CFDictionaryRef dict, const void * key) static
Referenced by ~OSXGL3PlusSupport().
static long Ogre::OSXGL3PlusSupport::_getDictionaryLong (CFDictionaryRef dict, const void * key) static
Referenced by ~OSXGL3PlusSupport().
void Ogre::OSXGL3PlusSupport::addConfig (void) virtual
Add any special config values to the system.
Must have a "Full Screen" value that is a bool and a "Video Mode" value that is a string in the form of wxh
Implements Ogre::GLNativeSupport.
Referenced by ~OSXGL3PlusSupport().
bool Ogre::GLNativeSupport::checkExtension (const String & ext) const inline inherited
virtual GLPBuffer* Ogre::GLNativeSupport::createPBuffer (PixelComponentType format, size_t width, size_t height) inline virtual inherited
Reimplemented in Ogre::X11EGLSupport, Ogre::EGLSupport, Ogre::GLXGLSupport, Ogre::Win32EGLSupport, and Ogre::AndroidEGLSupport.
RenderWindow* Ogre::OSXGL3PlusSupport::createWindow (bool autoCreateWindow, RenderSystem * renderSystem, const String & windowTitle) virtual
Implements Ogre::GLNativeSupport.
Referenced by ~OSXGL3PlusSupport().
ConfigOptionMap& Ogre::GLNativeSupport::getConfigOptions () inline inherited
virtual unsigned int Ogre::GLNativeSupport::getDisplayMonitorCount () const inline virtual inherited
Gets the number of display monitors.
See also
Root::getDisplayMonitorCount
Reimplemented in Ogre::Win32GLSupport.
void* Ogre::OSXGL3PlusSupport::getProcAddress (const char * name) virtual
Get the address of a function.
Implements Ogre::GLNativeSupport.
Referenced by ~OSXGL3PlusSupport().
virtual RenderWindow* Ogre::OSXGL3PlusSupport::newWindow (const String & name, unsigned int width, unsigned int height, bool fullScreen, const NameValuePairList * miscParams = 0) virtual
Implements Ogre::GLNativeSupport.
Referenced by ~OSXGL3PlusSupport().
virtual void Ogre::GLNativeSupport::setConfigOption (const String & name, const String & value) inline virtual inherited
Reimplemented in Ogre::EGLSupport, Ogre::EGLSupport, Ogre::GLXGLSupport, and Ogre::Win32GLSupport.
References Ogre::Exception::ERR_INVALIDPARAMS, and OGRE_EXCEPT.
void Ogre::OSXGL3PlusSupport::start () virtual
Start anything special.
Implements Ogre::GLNativeSupport.
Referenced by ~OSXGL3PlusSupport().
void Ogre::OSXGL3PlusSupport::stop () virtual
Stop anything special.
Implements Ogre::GLNativeSupport.
Referenced by ~OSXGL3PlusSupport().
String Ogre::OSXGL3PlusSupport::validateConfig (void) virtual
Make sure all the extra options are valid.
Implements Ogre::GLNativeSupport.
Referenced by ~OSXGL3PlusSupport().
Member Data Documentation
ExtensionList Ogre::GLNativeSupport::extensionList protected inherited
ContextProfile Ogre::GLNativeSupport::mContextProfile protected inherited
ConfigOptionMap Ogre::GLNativeSupport::mOptions protected inherited
The documentation for this class was generated from the following file:
OgreOSXGLSupport.h