OGRE: Ogre::CPreprocessor::Macro Class Reference
Ogre::CPreprocessor::Macro Class Reference
A macro definition.
Public Member Functions
Macro (const Token &iName)
Macro (const Token &iName)
~Macro ()
~Macro ()
Token Expand (int iNumArgs, Token *iArgs, Macro *iMacros)
Expand the macro value (will not work for functions)
Token Expand (int iNumArgs, Token *iArgs, Macro *iMacros)
Expand the macro value (will not work for functions)
Public Attributes
Token * Args
The names of the arguments.
Token Body
Unparsed macro body (keeps the whole raw unparsed macro body)
Token(* ExpandFunc)(CPreprocessor *iParent, int iNumArgs, Token *iArgs)
A pointer to function implementation (if macro is really a func)
bool Expanding
true if macro expansion is in progress
Token Name
Macro name.
Macro * Next
Next macro in chained list.
int NumArgs
Number of arguments.
Token Value
The macro value.
Detailed Description
A macro definition.
Constructor & Destructor Documentation
Ogre::CPreprocessor::Macro::Macro (const Token & iName) inline
Ogre::CPreprocessor::Macro::~Macro () inline
Ogre::CPreprocessor::Macro::Macro (const Token & iName) inline
Ogre::CPreprocessor::Macro::~Macro () inline
References Ogre::CPreprocessor::BOL, Ogre::CPreprocessor::CPreprocessor(), Ogre::CPreprocessor::EnableOutput, Ogre::CPreprocessor::Error(), Ogre::CPreprocessor::ExpandDefined(), Ogre::CPreprocessor::ExpandMacro(), Ogre::CPreprocessor::GetArgument(), Ogre::CPreprocessor::GetArguments(), Ogre::CPreprocessor::GetExpression(), Ogre::CPreprocessor::GetToken(), Ogre::CPreprocessor::Token::GetValue(), Ogre::CPreprocessor::HandleDefine(), Ogre::CPreprocessor::HandleDirective(), Ogre::CPreprocessor::HandleElse(), Ogre::CPreprocessor::HandleEndIf(), Ogre::CPreprocessor::HandleIf(), Ogre::CPreprocessor::HandleIfDef(), Ogre::CPreprocessor::HandleUnDef(), Ogre::CPreprocessor::IsDefined(), Ogre::CPreprocessor::Line, Ogre::CPreprocessor::MacroList, Ogre::CPreprocessor::Parse(), Ogre::CPreprocessor::Source, and Ogre::CPreprocessor::SourceEnd.
Member Function Documentation
Token Ogre::CPreprocessor::Macro::Expand (int iNumArgs, Token * iArgs, Macro * iMacros)
Expand the macro value (will not work for functions)
Token Ogre::CPreprocessor::Macro::Expand (int iNumArgs, Token * iArgs, Macro * iMacros)
Expand the macro value (will not work for functions)
Member Data Documentation
Token * Ogre::CPreprocessor::Macro::Args
The names of the arguments.
Token Ogre::CPreprocessor::Macro::Body
Unparsed macro body (keeps the whole raw unparsed macro body)
Token(* Ogre::CPreprocessor::Macro::ExpandFunc)(CPreprocessor *iParent, int iNumArgs, Token *iArgs)
A pointer to function implementation (if macro is really a func)
bool Ogre::CPreprocessor::Macro::Expanding
true if macro expansion is in progress
Token Ogre::CPreprocessor::Macro::Name
Macro name.
Macro * Ogre::CPreprocessor::Macro::Next
Next macro in chained list.
int Ogre::CPreprocessor::Macro::NumArgs
Number of arguments.
Token Ogre::CPreprocessor::Macro::Value
The macro value.
The documentation for this class was generated from the following files:
Plus/include/GLSL/OgreGLSLPreprocessor.h
OgreGLSLESPreprocessor.h