OGRE: Ogre::GLES2StateCacheManagerImp Class Reference
Ogre::GLES2StateCacheManagerImp Class Reference
An in memory cache of the OpenGL ES state.
#include <OgreGLES2StateCacheManagerImp.h>
Classes
struct TextureUnitParams
Public Member Functions
GLES2StateCacheManagerImp (void)
GLES2StateCacheManagerImp (void)
~GLES2StateCacheManagerImp (void)
~GLES2StateCacheManagerImp (void)
bool activateGLTextureUnit (unsigned char unit)
See GLES2StateCacheManager.activateGLTextureUnit.
bool activateGLTextureUnit (size_t unit)
See GLES2StateCacheManager.activateGLTextureUnit.
void bindGLBuffer (GLenum target, GLuint buffer, bool force=false)
See GLES2StateCacheManager.bindGLBuffer.
void bindGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLES2StateCacheManager.bindGLBuffer.
void bindGLTexture (GLenum target, GLuint texture)
See GLES2StateCacheManager.bindGLTexture.
void bindGLTexture (GLenum target, GLuint texture)
See GLES2StateCacheManager.bindGLTexture.
void clearCache ()
See GLES2StateCacheManager.clearCache.
void clearCache ()
See GLES2StateCacheManager.clearCache.
void deleteGLBuffer (GLenum target, GLuint buffer, bool force=false)
See GLES2StateCacheManager.deleteGLBuffer.
void deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLES2StateCacheManager.deleteGLBuffer.
GLenum getBlendEquation (void) const
See GLES2StateCacheManager.getBlendEquation.
GLenum getBlendEquation (void) const
See GLES2StateCacheManager.getBlendEquation.
GLclampf getClearDepth (void) const
See GLES2StateCacheManager.getClearDepth.
GLclampf getClearDepth (void) const
See GLES2StateCacheManager.getClearDepth.
vector< GLboolean >::type & getColourMask (void)
See GLES2StateCacheManager.getColourMask.
vector< GLboolean >::type & getColourMask (void)
See GLES2StateCacheManager.getColourMask.
GLenum getCullFace (void) const
See GLES2StateCacheManager.getCullFace.
GLenum getCullFace (void) const
See GLES2StateCacheManager.getCullFace.
GLenum getDepthFunc (void) const
See GLES2StateCacheManager.getDepthFunc.
GLenum getDepthFunc (void) const
See GLES2StateCacheManager.getDepthFunc.
GLboolean getDepthMask (void) const
See GLES2StateCacheManager.getDepthMask.
GLboolean getDepthMask (void) const
See GLES2StateCacheManager.getDepthMask.
unsigned int getDiscardBuffers (void) const
See GLES2StateCacheManager.getDiscardBuffers.
unsigned int getDiscardBuffers (void) const
See GLES2StateCacheManager.getDiscardBuffers.
GLenum getPolygonMode (void) const
See GLES2StateCacheManager.getPolygonMode.
GLenum getPolygonMode (void) const
See GLES2StateCacheManager.getPolygonMode.
GLuint getStencilMask (void) const
See GLES2StateCacheManager.getStencilMask.
GLuint getStencilMask (void) const
See GLES2StateCacheManager.getStencilMask.
void getTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
See GLES2StateCacheManager.getTexParameterfv.
void getTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
See GLES2StateCacheManager.getTexParameterfv.
void initializeCache ()
See GLES2StateCacheManager.initializeCache.
void initializeCache ()
See GLES2StateCacheManager.initializeCache.
void invalidateStateForTexture (GLuint texture)
See GLES2StateCacheManager.invalidateStateForTexture.
void invalidateStateForTexture (GLuint texture)
See GLES2StateCacheManager.invalidateStateForTexture.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void setBlendEquation (GLenum eq)
See GLES2StateCacheManager.setBlendEquation.
void setBlendEquation (GLenum eq)
See GLES2StateCacheManager.setBlendEquation.
void setBlendFunc (GLenum source, GLenum dest)
See GLES2StateCacheManager.setBlendFunc.
void setBlendFunc (GLenum source, GLenum dest)
See GLES2StateCacheManager.setBlendFunc.
void setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLES2StateCacheManager.setClearColour.
void setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLES2StateCacheManager.setClearColour.
void setClearDepth (GLclampf depth)
See GLES2StateCacheManager.setClearDepth.
void setClearDepth (GLclampf depth)
See GLES2StateCacheManager.setClearDepth.
void setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLES2StateCacheManager.setColourMask.
void setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLES2StateCacheManager.setColourMask.
void setCullFace (GLenum face)
See GLES2StateCacheManager.setCullFace.
void setCullFace (GLenum face)
See GLES2StateCacheManager.setCullFace.
void setDepthFunc (GLenum func)
See GLES2StateCacheManager.setDepthFunc.
void setDepthFunc (GLenum func)
See GLES2StateCacheManager.setDepthFunc.
void setDepthMask (GLboolean mask)
See GLES2StateCacheManager.setDepthMask.
void setDepthMask (GLboolean mask)
See GLES2StateCacheManager.setDepthMask.
void setDisabled (GLenum flag)
See GLES2StateCacheManager.setDisabled.
void setDisabled (GLenum flag)
See GLES2StateCacheManager.setDisabled.
void setDiscardBuffers (unsigned int flags)
See GLES2StateCacheManager.setDiscardBuffers.
void setDiscardBuffers (unsigned int flags)
See GLES2StateCacheManager.setDiscardBuffers.
void setEnabled (GLenum flag)
See GLES2StateCacheManager.setEnabled.
void setEnabled (GLenum flag)
See GLES2StateCacheManager.setEnabled.
void setPolygonMode (GLenum mode)
See GLES2StateCacheManager.setPolygonMode.
void setPolygonMode (GLenum mode)
See GLES2StateCacheManager.setPolygonMode.
void setStencilMask (GLuint mask)
See GLES2StateCacheManager.setStencilMask.
void setStencilMask (GLuint mask)
See GLES2StateCacheManager.setStencilMask.
void setTexParameterf (GLenum target, GLenum pname, GLfloat params)
See GLES2StateCacheManager.setTexParameterf.
void setTexParameterf (GLenum target, GLenum pname, GLfloat params)
See GLES2StateCacheManager.setTexParameterf.
void setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLES2StateCacheManager.setTexParameteri.
void setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLES2StateCacheManager.setTexParameteri.
void setVertexAttribDisabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribDisabled.
void setVertexAttribDisabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribDisabled.
void setVertexAttribEnabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribEnabled.
void setVertexAttribEnabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribEnabled.
Private Types
typedef OGRE_HashMap< GLenum, GLuint > BindBufferMap
typedef OGRE_HashMap< GLenum, GLfloat > TexParameterfMap
typedef OGRE_HashMap< GLenum, GLint > TexParameteriMap
typedef OGRE_HashMap< GLuint, TextureUnitParams > TexUnitsMap
Private Attributes
BindBufferMap mActiveBufferMap
A map of different buffer types and the currently bound buffer for each type.
unsigned char mActiveTextureUnit
Stores the currently active texture unit.
GLenum mActiveTextureUnit
Stores the currently active texture unit.
GLenum mBlendEquation
Stores the current blend equation.
GLenum mBlendFuncDest
Stores the current blend destination function.
GLenum mBlendFuncSource
Stores the current blend source function.
vector< GLclampf >::type mClearColour
Stores the current clear colour.
GLclampf mClearDepth
Stores the current depth clearing colour.
vector< GLboolean >::type mColourMask
Stores the current colour write mask.
GLenum mCullFace
Stores the current face culling setting.
GLenum mDepthFunc
Stores the current depth test function.
GLboolean mDepthMask
Stores the current depth write mask.
unsigned int mDiscardBuffers
Mask of buffers who contents can be discarded if GL_EXT_discard_framebuffer is supported.
vector< GLuint >::type mEnabledVertexAttribs
Stores the currently enabled vertex attributes.
vector< GLenum >::type mEnableVector
Array of each OpenGL feature that is enabled i.e. blending, depth test, etc.
GLuint mLastBoundTexID
Stores the last bound texture id.
GLenum mPolygonMode
Stores the current polygon rendering mode.
GLuint mStencilMask
Stores the current stencil mask.
TexUnitsMap mTexUnitsMap
A map of texture parameters for each texture unit.
Detailed Description
An in memory cache of the OpenGL ES state.
An in memory cache of the OpenGL ES2 state.
See also
GLES2StateCacheManager
Member Typedef Documentation
typedef OGRE_HashMap<GLenum, GLuint> Ogre::GLES2StateCacheManagerImp::BindBufferMap private
typedef OGRE_HashMap<GLenum, GLfloat> Ogre::GLES2StateCacheManagerImp::TexParameterfMap private
typedef OGRE_HashMap<GLenum, GLint> Ogre::GLES2StateCacheManagerImp::TexParameteriMap private
typedef OGRE_HashMap<GLuint, TextureUnitParams> Ogre::GLES2StateCacheManagerImp::TexUnitsMap private
Constructor & Destructor Documentation
Ogre::GLES2StateCacheManagerImp::GLES2StateCacheManagerImp (void)
Ogre::GLES2StateCacheManagerImp::~GLES2StateCacheManagerImp (void)
Ogre::GLES2StateCacheManagerImp::GLES2StateCacheManagerImp (void)
Ogre::GLES2StateCacheManagerImp::~GLES2StateCacheManagerImp (void)
Member Function Documentation
bool Ogre::GLES2StateCacheManagerImp::activateGLTextureUnit (unsigned char unit)
See GLES2StateCacheManager.activateGLTextureUnit.
bool Ogre::GLES2StateCacheManagerImp::activateGLTextureUnit (size_t unit)
See GLES2StateCacheManager.activateGLTextureUnit.
void Ogre::GLES2StateCacheManagerImp::bindGLBuffer (GLenum target, GLuint buffer, bool force = false)
See GLES2StateCacheManager.bindGLBuffer.
void Ogre::GLES2StateCacheManagerImp::bindGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLES2StateCacheManager.bindGLBuffer.
void Ogre::GLES2StateCacheManagerImp::bindGLTexture (GLenum target, GLuint texture)
See GLES2StateCacheManager.bindGLTexture.
void Ogre::GLES2StateCacheManagerImp::bindGLTexture (GLenum target, GLuint texture)
See GLES2StateCacheManager.bindGLTexture.
void Ogre::GLES2StateCacheManagerImp::clearCache ()
See GLES2StateCacheManager.clearCache.
void Ogre::GLES2StateCacheManagerImp::clearCache ()
See GLES2StateCacheManager.clearCache.
void Ogre::GLES2StateCacheManagerImp::deleteGLBuffer (GLenum target, GLuint buffer, bool force = false)
See GLES2StateCacheManager.deleteGLBuffer.
void Ogre::GLES2StateCacheManagerImp::deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLES2StateCacheManager.deleteGLBuffer.
GLenum Ogre::GLES2StateCacheManagerImp::getBlendEquation (void) const inline
See GLES2StateCacheManager.getBlendEquation.
References mBlendEquation, setBlendEquation(), and setBlendFunc().
GLenum Ogre::GLES2StateCacheManagerImp::getBlendEquation (void) const inline
See GLES2StateCacheManager.getBlendEquation.
GLclampf Ogre::GLES2StateCacheManagerImp::getClearDepth (void) const inline
See GLES2StateCacheManager.getClearDepth.
References mClearDepth, setClearColour(), and setClearDepth().
GLclampf Ogre::GLES2StateCacheManagerImp::getClearDepth (void) const inline
See GLES2StateCacheManager.getClearDepth.
vector<GLboolean>::type& Ogre::GLES2StateCacheManagerImp::getColourMask (void) inline
See GLES2StateCacheManager.getColourMask.
References mColourMask, and setColourMask().
vector<GLboolean>::type& Ogre::GLES2StateCacheManagerImp::getColourMask (void) inline
See GLES2StateCacheManager.getColourMask.
GLenum Ogre::GLES2StateCacheManagerImp::getCullFace (void) const inline
See GLES2StateCacheManager.getCullFace.
References mCullFace, and setCullFace().
GLenum Ogre::GLES2StateCacheManagerImp::getCullFace (void) const inline
See GLES2StateCacheManager.getCullFace.
GLenum Ogre::GLES2StateCacheManagerImp::getDepthFunc (void) const inline
See GLES2StateCacheManager.getDepthFunc.
References mDepthFunc, and setDepthFunc().
GLenum Ogre::GLES2StateCacheManagerImp::getDepthFunc (void) const inline
See GLES2StateCacheManager.getDepthFunc.
GLboolean Ogre::GLES2StateCacheManagerImp::getDepthMask (void) const inline
See GLES2StateCacheManager.getDepthMask.
References mDepthMask, and setDepthMask().
GLboolean Ogre::GLES2StateCacheManagerImp::getDepthMask (void) const inline
See GLES2StateCacheManager.getDepthMask.
unsigned int Ogre::GLES2StateCacheManagerImp::getDiscardBuffers (void) const inline
See GLES2StateCacheManager.getDiscardBuffers.
References mDiscardBuffers.
unsigned int Ogre::GLES2StateCacheManagerImp::getDiscardBuffers (void) const inline
See GLES2StateCacheManager.getDiscardBuffers.
GLenum Ogre::GLES2StateCacheManagerImp::getPolygonMode (void) const inline
See GLES2StateCacheManager.getPolygonMode.
References mPolygonMode.
GLenum Ogre::GLES2StateCacheManagerImp::getPolygonMode (void) const inline
See GLES2StateCacheManager.getPolygonMode.
GLuint Ogre::GLES2StateCacheManagerImp::getStencilMask (void) const inline
See GLES2StateCacheManager.getStencilMask.
References mStencilMask, setDisabled(), setEnabled(), setStencilMask(), setVertexAttribDisabled(), and setVertexAttribEnabled().
GLuint Ogre::GLES2StateCacheManagerImp::getStencilMask (void) const inline
See GLES2StateCacheManager.getStencilMask.
void Ogre::GLES2StateCacheManagerImp::getTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
See GLES2StateCacheManager.getTexParameterfv.
void Ogre::GLES2StateCacheManagerImp::getTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
See GLES2StateCacheManager.getTexParameterfv.
void Ogre::GLES2StateCacheManagerImp::initializeCache ()
See GLES2StateCacheManager.initializeCache.
void Ogre::GLES2StateCacheManagerImp::initializeCache ()
See GLES2StateCacheManager.initializeCache.
void Ogre::GLES2StateCacheManagerImp::invalidateStateForTexture (GLuint texture)
See GLES2StateCacheManager.invalidateStateForTexture.
void Ogre::GLES2StateCacheManagerImp::invalidateStateForTexture (GLuint texture)
See GLES2StateCacheManager.invalidateStateForTexture.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
void Ogre::GLES2StateCacheManagerImp::setBlendEquation (GLenum eq)
See GLES2StateCacheManager.setBlendEquation.
Referenced by getBlendEquation().
void Ogre::GLES2StateCacheManagerImp::setBlendEquation (GLenum eq)
See GLES2StateCacheManager.setBlendEquation.
void Ogre::GLES2StateCacheManagerImp::setBlendFunc (GLenum source, GLenum dest)
See GLES2StateCacheManager.setBlendFunc.
Referenced by getBlendEquation().
void Ogre::GLES2StateCacheManagerImp::setBlendFunc (GLenum source, GLenum dest)
See GLES2StateCacheManager.setBlendFunc.
void Ogre::GLES2StateCacheManagerImp::setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLES2StateCacheManager.setClearColour.
Referenced by getClearDepth().
void Ogre::GLES2StateCacheManagerImp::setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLES2StateCacheManager.setClearColour.
void Ogre::GLES2StateCacheManagerImp::setClearDepth (GLclampf depth)
See GLES2StateCacheManager.setClearDepth.
Referenced by getClearDepth().
void Ogre::GLES2StateCacheManagerImp::setClearDepth (GLclampf depth)
See GLES2StateCacheManager.setClearDepth.
void Ogre::GLES2StateCacheManagerImp::setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLES2StateCacheManager.setColourMask.
Referenced by getColourMask().
void Ogre::GLES2StateCacheManagerImp::setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLES2StateCacheManager.setColourMask.
void Ogre::GLES2StateCacheManagerImp::setCullFace (GLenum face)
See GLES2StateCacheManager.setCullFace.
Referenced by getCullFace().
void Ogre::GLES2StateCacheManagerImp::setCullFace (GLenum face)
See GLES2StateCacheManager.setCullFace.
void Ogre::GLES2StateCacheManagerImp::setDepthFunc (GLenum func)
See GLES2StateCacheManager.setDepthFunc.
Referenced by getDepthFunc().
void Ogre::GLES2StateCacheManagerImp::setDepthFunc (GLenum func)
See GLES2StateCacheManager.setDepthFunc.
void Ogre::GLES2StateCacheManagerImp::setDepthMask (GLboolean mask)
See GLES2StateCacheManager.setDepthMask.
Referenced by getDepthMask().
void Ogre::GLES2StateCacheManagerImp::setDepthMask (GLboolean mask)
See GLES2StateCacheManager.setDepthMask.
void Ogre::GLES2StateCacheManagerImp::setDisabled (GLenum flag)
See GLES2StateCacheManager.setDisabled.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setDisabled (GLenum flag)
See GLES2StateCacheManager.setDisabled.
void Ogre::GLES2StateCacheManagerImp::setDiscardBuffers (unsigned int flags) inline
See GLES2StateCacheManager.setDiscardBuffers.
void Ogre::GLES2StateCacheManagerImp::setDiscardBuffers (unsigned int flags) inline
See GLES2StateCacheManager.setDiscardBuffers.
void Ogre::GLES2StateCacheManagerImp::setEnabled (GLenum flag)
See GLES2StateCacheManager.setEnabled.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setEnabled (GLenum flag)
See GLES2StateCacheManager.setEnabled.
void Ogre::GLES2StateCacheManagerImp::setPolygonMode (GLenum mode) inline
See GLES2StateCacheManager.setPolygonMode.
void Ogre::GLES2StateCacheManagerImp::setPolygonMode (GLenum mode) inline
See GLES2StateCacheManager.setPolygonMode.
void Ogre::GLES2StateCacheManagerImp::setStencilMask (GLuint mask)
See GLES2StateCacheManager.setStencilMask.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setStencilMask (GLuint mask)
See GLES2StateCacheManager.setStencilMask.
void Ogre::GLES2StateCacheManagerImp::setTexParameterf (GLenum target, GLenum pname, GLfloat params)
See GLES2StateCacheManager.setTexParameterf.
void Ogre::GLES2StateCacheManagerImp::setTexParameterf (GLenum target, GLenum pname, GLfloat params)
See GLES2StateCacheManager.setTexParameterf.
void Ogre::GLES2StateCacheManagerImp::setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLES2StateCacheManager.setTexParameteri.
void Ogre::GLES2StateCacheManagerImp::setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLES2StateCacheManager.setTexParameteri.
void Ogre::GLES2StateCacheManagerImp::setVertexAttribDisabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribDisabled.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setVertexAttribDisabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribDisabled.
void Ogre::GLES2StateCacheManagerImp::setVertexAttribEnabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribEnabled.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setVertexAttribEnabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribEnabled.
Member Data Documentation
BindBufferMap Ogre::GLES2StateCacheManagerImp::mActiveBufferMap private
A map of different buffer types and the currently bound buffer for each type.
unsigned char Ogre::GLES2StateCacheManagerImp::mActiveTextureUnit private
Stores the currently active texture unit.
GLenum Ogre::GLES2StateCacheManagerImp::mActiveTextureUnit private
Stores the currently active texture unit.
GLenum Ogre::GLES2StateCacheManagerImp::mBlendEquation private
Stores the current blend equation.
Referenced by getBlendEquation().
GLenum Ogre::GLES2StateCacheManagerImp::mBlendFuncDest private
Stores the current blend destination function.
GLenum Ogre::GLES2StateCacheManagerImp::mBlendFuncSource private
Stores the current blend source function.
vector< GLclampf >::type Ogre::GLES2StateCacheManagerImp::mClearColour private
Stores the current clear colour.
GLclampf Ogre::GLES2StateCacheManagerImp::mClearDepth private
Stores the current depth clearing colour.
Referenced by getClearDepth().
vector< GLboolean >::type Ogre::GLES2StateCacheManagerImp::mColourMask private
Stores the current colour write mask.
Referenced by getColourMask().
GLenum Ogre::GLES2StateCacheManagerImp::mCullFace private
Stores the current face culling setting.
Referenced by getCullFace().
GLenum Ogre::GLES2StateCacheManagerImp::mDepthFunc private
Stores the current depth test function.
Referenced by getDepthFunc().
GLboolean Ogre::GLES2StateCacheManagerImp::mDepthMask private
Stores the current depth write mask.
Referenced by getDepthMask().
unsigned int Ogre::GLES2StateCacheManagerImp::mDiscardBuffers private
Mask of buffers who contents can be discarded if GL_EXT_discard_framebuffer is supported.
Referenced by getDiscardBuffers().
vector<GLuint>::type Ogre::GLES2StateCacheManagerImp::mEnabledVertexAttribs private
Stores the currently enabled vertex attributes.
vector<GLenum>::type Ogre::GLES2StateCacheManagerImp::mEnableVector private
Array of each OpenGL feature that is enabled i.e. blending, depth test, etc.
GLuint Ogre::GLES2StateCacheManagerImp::mLastBoundTexID private
Stores the last bound texture id.
GLenum Ogre::GLES2StateCacheManagerImp::mPolygonMode private
Stores the current polygon rendering mode.
Referenced by getPolygonMode().
GLuint Ogre::GLES2StateCacheManagerImp::mStencilMask private
Stores the current stencil mask.
Referenced by getStencilMask().
TexUnitsMap Ogre::GLES2StateCacheManagerImp::mTexUnitsMap private
A map of texture parameters for each texture unit.
The documentation for this class was generated from the following files:
OgreGLES2NullStateCacheManagerImp.h
OgreGLES2StateCacheManagerImp.h