OGRE: Ogre::GLESStateCacheManagerImp Class Reference
Ogre::GLESStateCacheManagerImp Class Reference
An in memory cache of the OpenGL ES state.
#include <OgreGLESStateCacheManagerImp.h>
Classes
struct TextureUnitParams
Public Member Functions
GLESStateCacheManagerImp (void)
GLESStateCacheManagerImp (void)
~GLESStateCacheManagerImp (void)
~GLESStateCacheManagerImp (void)
bool activateGLTextureUnit (unsigned char unit)
See GLESStateCacheManager.activateGLTextureUnit.
bool activateGLTextureUnit (unsigned char unit)
See GLESStateCacheManager.activateGLTextureUnit.
void bindGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLESStateCacheManager.bindGLBuffer.
void bindGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLESStateCacheManager.bindGLBuffer.
void bindGLTexture (GLenum target, GLuint texture)
See GLESStateCacheManager.bindGLTexture.
void bindGLTexture (GLenum target, GLuint texture)
See GLESStateCacheManager.bindGLTexture.
void clearCache ()
See GLESStateCacheManager.clearCache.
void clearCache ()
See GLESStateCacheManager.clearCache.
void deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLESStateCacheManager.deleteGLBuffer.
void deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLESStateCacheManager.deleteGLBuffer.
GLenum getBlendEquation (void) const
See GLESStateCacheManager.getBlendEquation.
GLenum getBlendEquation (void) const
See GLESStateCacheManager.getBlendEquation.
GLclampf getClearDepth (void) const
See GLESStateCacheManager.getClearDepth.
GLclampf getClearDepth (void) const
See GLESStateCacheManager.getClearDepth.
vector< GLboolean >::type & getColourMask (void)
See GLESStateCacheManager.getColourMask.
vector< GLboolean >::type & getColourMask (void)
See GLESStateCacheManager.getColourMask.
GLenum getCullFace (void) const
See GLESStateCacheManager.getCullFace.
GLenum getCullFace (void) const
See GLESStateCacheManager.getCullFace.
GLenum getDepthFunc (void) const
See GLESStateCacheManager.getDepthFunc.
GLenum getDepthFunc (void) const
See GLESStateCacheManager.getDepthFunc.
GLboolean getDepthMask (void) const
See GLESStateCacheManager.getDepthMask.
GLboolean getDepthMask (void) const
See GLESStateCacheManager.getDepthMask.
unsigned int getDiscardBuffers (void) const
See GLESStateCacheManager.getDiscardBuffers.
unsigned int getDiscardBuffers (void) const
See GLESStateCacheManager.getDiscardBuffers.
GLenum getPolygonMode (void) const
See GLESStateCacheManager.getPolygonMode.
GLenum getPolygonMode (void) const
See GLESStateCacheManager.getPolygonMode.
GLuint getStencilMask (void) const
See GLESStateCacheManager.getStencilMask.
GLuint getStencilMask (void) const
See GLESStateCacheManager.getStencilMask.
void initializeCache ()
See GLESStateCacheManager.initializeCache.
void initializeCache ()
See GLESStateCacheManager.initializeCache.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void setBlendEquation (GLenum eq)
See GLESStateCacheManager.setBlendEquation.
void setBlendEquation (GLenum eq)
See GLESStateCacheManager.setBlendEquation.
void setBlendFunc (GLenum source, GLenum dest)
See GLESStateCacheManager.setBlendFunc.
void setBlendFunc (GLenum source, GLenum dest)
See GLESStateCacheManager.setBlendFunc.
void setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLESStateCacheManager.setClearColour.
void setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLESStateCacheManager.setClearColour.
void setClearDepth (GLclampf depth)
See GLESStateCacheManager.setClearDepth.
void setClearDepth (GLclampf depth)
See GLESStateCacheManager.setClearDepth.
void setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLESStateCacheManager.setColourMask.
void setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLESStateCacheManager.setColourMask.
void setCullFace (GLenum face)
See GLESStateCacheManager.setCullFace.
void setCullFace (GLenum face)
See GLESStateCacheManager.setCullFace.
void setDepthFunc (GLenum func)
See GLESStateCacheManager.setDepthFunc.
void setDepthFunc (GLenum func)
See GLESStateCacheManager.setDepthFunc.
void setDepthMask (GLboolean mask)
See GLESStateCacheManager.setDepthMask.
void setDepthMask (GLboolean mask)
See GLESStateCacheManager.setDepthMask.
void setDisabled (GLenum flag)
See GLESStateCacheManager.setDisabled.
void setDisabled (GLenum flag)
See GLESStateCacheManager.setDisabled.
void setDiscardBuffers (unsigned int flags)
See GLESStateCacheManager.setDiscardBuffers.
void setDiscardBuffers (unsigned int flags)
See GLESStateCacheManager.setDiscardBuffers.
void setEnabled (GLenum flag)
See GLESStateCacheManager.setEnabled.
void setEnabled (GLenum flag)
See GLESStateCacheManager.setEnabled.
void setPolygonMode (GLenum mode)
See GLESStateCacheManager.setPolygonMode.
void setPolygonMode (GLenum mode)
See GLESStateCacheManager.setPolygonMode.
void setStencilMask (GLuint mask)
See GLESStateCacheManager.setStencilMask.
void setStencilMask (GLuint mask)
See GLESStateCacheManager.setStencilMask.
void setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLESStateCacheManager.setTexParameteri.
void setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLESStateCacheManager.setTexParameteri.
Private Types
typedef OGRE_HashMap< GLuint, GLuint > GLBindingMap
typedef OGRE_HashMap< GLenum, GLint > TexParameteriMap
typedef OGRE_HashMap< GLuint, TextureUnitParams > TexUnitsMap
Private Attributes
GLBindingMap mActiveBufferMap
A map of different buffer types and the currently bound buffer for each type.
GLBindingMap mActiveTextureMap
A map of different texture types and the currently bound texture for each type.
unsigned char mActiveTextureUnit
Stores the currently active texture unit.
GLenum mBlendEquation
Stores the current blend equation.
GLenum mBlendFuncDest
GLenum mBlendFuncSrc
Stores the current blend function.
vector< GLclampf >::type mClearColour
Stores the current clear colour.
GLclampf mClearDepth
Stores the current depth clearing colour.
vector< GLboolean >::type mColourMask
Stores the current colour write mask.
GLenum mCullFace
Stores the current face culling setting.
GLenum mDepthFunc
Stores the current depth test function.
GLboolean mDepthMask
Stores the current depth write mask.
unsigned int mDiscardBuffers
Mask of buffers who contents can be discarded if GL_EXT_discard_framebuffer is supported.
vector< GLenum >::type mEnableVector
Array of each OpenGL feature that is enabled i.e. blending, depth test, etc.
GLuint mLastBoundedTexID
Stores the last bounded texture id.
GLenum mPolygonMode
Stores the current polygon rendering mode.
GLuint mStencilMask
Stores the current stencil mask.
TexUnitsMap mTexUnitsMap
A map of texture parameters for each texture unit.
Detailed Description
An in memory cache of the OpenGL ES state.
See also
GLESStateCacheManager
Member Typedef Documentation
typedef OGRE_HashMap<GLuint, GLuint> Ogre::GLESStateCacheManagerImp::GLBindingMap private
typedef OGRE_HashMap<GLenum, GLint> Ogre::GLESStateCacheManagerImp::TexParameteriMap private
typedef OGRE_HashMap<GLuint, TextureUnitParams> Ogre::GLESStateCacheManagerImp::TexUnitsMap private
Constructor & Destructor Documentation
Ogre::GLESStateCacheManagerImp::GLESStateCacheManagerImp (void)
Ogre::GLESStateCacheManagerImp::~GLESStateCacheManagerImp (void)
Ogre::GLESStateCacheManagerImp::GLESStateCacheManagerImp (void)
Ogre::GLESStateCacheManagerImp::~GLESStateCacheManagerImp (void)
Member Function Documentation
bool Ogre::GLESStateCacheManagerImp::activateGLTextureUnit (unsigned char unit)
See GLESStateCacheManager.activateGLTextureUnit.
bool Ogre::GLESStateCacheManagerImp::activateGLTextureUnit (unsigned char unit)
See GLESStateCacheManager.activateGLTextureUnit.
void Ogre::GLESStateCacheManagerImp::bindGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLESStateCacheManager.bindGLBuffer.
void Ogre::GLESStateCacheManagerImp::bindGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLESStateCacheManager.bindGLBuffer.
void Ogre::GLESStateCacheManagerImp::bindGLTexture (GLenum target, GLuint texture)
See GLESStateCacheManager.bindGLTexture.
void Ogre::GLESStateCacheManagerImp::bindGLTexture (GLenum target, GLuint texture)
See GLESStateCacheManager.bindGLTexture.
void Ogre::GLESStateCacheManagerImp::clearCache ()
See GLESStateCacheManager.clearCache.
void Ogre::GLESStateCacheManagerImp::clearCache ()
See GLESStateCacheManager.clearCache.
void Ogre::GLESStateCacheManagerImp::deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLESStateCacheManager.deleteGLBuffer.
void Ogre::GLESStateCacheManagerImp::deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLESStateCacheManager.deleteGLBuffer.
GLenum Ogre::GLESStateCacheManagerImp::getBlendEquation (void) const inline
See GLESStateCacheManager.getBlendEquation.
References mBlendEquation, setBlendEquation(), and setBlendFunc().
GLenum Ogre::GLESStateCacheManagerImp::getBlendEquation (void) const inline
See GLESStateCacheManager.getBlendEquation.
GLclampf Ogre::GLESStateCacheManagerImp::getClearDepth (void) const inline
See GLESStateCacheManager.getClearDepth.
References mClearDepth, setClearColour(), and setClearDepth().
GLclampf Ogre::GLESStateCacheManagerImp::getClearDepth (void) const inline
See GLESStateCacheManager.getClearDepth.
vector<GLboolean>::type& Ogre::GLESStateCacheManagerImp::getColourMask (void) inline
See GLESStateCacheManager.getColourMask.
References mColourMask, and setColourMask().
vector<GLboolean>::type& Ogre::GLESStateCacheManagerImp::getColourMask (void) inline
See GLESStateCacheManager.getColourMask.
GLenum Ogre::GLESStateCacheManagerImp::getCullFace (void) const inline
See GLESStateCacheManager.getCullFace.
References mCullFace, and setCullFace().
GLenum Ogre::GLESStateCacheManagerImp::getCullFace (void) const inline
See GLESStateCacheManager.getCullFace.
GLenum Ogre::GLESStateCacheManagerImp::getDepthFunc (void) const inline
See GLESStateCacheManager.getDepthFunc.
References mDepthFunc, and setDepthFunc().
GLenum Ogre::GLESStateCacheManagerImp::getDepthFunc (void) const inline
See GLESStateCacheManager.getDepthFunc.
GLboolean Ogre::GLESStateCacheManagerImp::getDepthMask (void) const inline
See GLESStateCacheManager.getDepthMask.
References mDepthMask, and setDepthMask().
GLboolean Ogre::GLESStateCacheManagerImp::getDepthMask (void) const inline
See GLESStateCacheManager.getDepthMask.
unsigned int Ogre::GLESStateCacheManagerImp::getDiscardBuffers (void) const inline
See GLESStateCacheManager.getDiscardBuffers.
References mDiscardBuffers.
unsigned int Ogre::GLESStateCacheManagerImp::getDiscardBuffers (void) const inline
See GLESStateCacheManager.getDiscardBuffers.
GLenum Ogre::GLESStateCacheManagerImp::getPolygonMode (void) const inline
See GLESStateCacheManager.getPolygonMode.
References mPolygonMode.
GLenum Ogre::GLESStateCacheManagerImp::getPolygonMode (void) const inline
See GLESStateCacheManager.getPolygonMode.
GLuint Ogre::GLESStateCacheManagerImp::getStencilMask (void) const inline
See GLESStateCacheManager.getStencilMask.
References mStencilMask, setDisabled(), setEnabled(), and setStencilMask().
GLuint Ogre::GLESStateCacheManagerImp::getStencilMask (void) const inline
See GLESStateCacheManager.getStencilMask.
void Ogre::GLESStateCacheManagerImp::initializeCache ()
See GLESStateCacheManager.initializeCache.
void Ogre::GLESStateCacheManagerImp::initializeCache ()
See GLESStateCacheManager.initializeCache.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
void Ogre::GLESStateCacheManagerImp::setBlendEquation (GLenum eq)
See GLESStateCacheManager.setBlendEquation.
Referenced by getBlendEquation().
void Ogre::GLESStateCacheManagerImp::setBlendEquation (GLenum eq)
See GLESStateCacheManager.setBlendEquation.
void Ogre::GLESStateCacheManagerImp::setBlendFunc (GLenum source, GLenum dest)
See GLESStateCacheManager.setBlendFunc.
Referenced by getBlendEquation().
void Ogre::GLESStateCacheManagerImp::setBlendFunc (GLenum source, GLenum dest)
See GLESStateCacheManager.setBlendFunc.
void Ogre::GLESStateCacheManagerImp::setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLESStateCacheManager.setClearColour.
Referenced by getClearDepth().
void Ogre::GLESStateCacheManagerImp::setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLESStateCacheManager.setClearColour.
void Ogre::GLESStateCacheManagerImp::setClearDepth (GLclampf depth)
See GLESStateCacheManager.setClearDepth.
Referenced by getClearDepth().
void Ogre::GLESStateCacheManagerImp::setClearDepth (GLclampf depth)
See GLESStateCacheManager.setClearDepth.
void Ogre::GLESStateCacheManagerImp::setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLESStateCacheManager.setColourMask.
Referenced by getColourMask().
void Ogre::GLESStateCacheManagerImp::setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLESStateCacheManager.setColourMask.
void Ogre::GLESStateCacheManagerImp::setCullFace (GLenum face)
See GLESStateCacheManager.setCullFace.
Referenced by getCullFace().
void Ogre::GLESStateCacheManagerImp::setCullFace (GLenum face)
See GLESStateCacheManager.setCullFace.
void Ogre::GLESStateCacheManagerImp::setDepthFunc (GLenum func)
See GLESStateCacheManager.setDepthFunc.
Referenced by getDepthFunc().
void Ogre::GLESStateCacheManagerImp::setDepthFunc (GLenum func)
See GLESStateCacheManager.setDepthFunc.
void Ogre::GLESStateCacheManagerImp::setDepthMask (GLboolean mask)
See GLESStateCacheManager.setDepthMask.
Referenced by getDepthMask().
void Ogre::GLESStateCacheManagerImp::setDepthMask (GLboolean mask)
See GLESStateCacheManager.setDepthMask.
void Ogre::GLESStateCacheManagerImp::setDisabled (GLenum flag)
See GLESStateCacheManager.setDisabled.
Referenced by getStencilMask().
void Ogre::GLESStateCacheManagerImp::setDisabled (GLenum flag)
See GLESStateCacheManager.setDisabled.
void Ogre::GLESStateCacheManagerImp::setDiscardBuffers (unsigned int flags) inline
See GLESStateCacheManager.setDiscardBuffers.
void Ogre::GLESStateCacheManagerImp::setDiscardBuffers (unsigned int flags) inline
See GLESStateCacheManager.setDiscardBuffers.
void Ogre::GLESStateCacheManagerImp::setEnabled (GLenum flag)
See GLESStateCacheManager.setEnabled.
Referenced by getStencilMask().
void Ogre::GLESStateCacheManagerImp::setEnabled (GLenum flag)
See GLESStateCacheManager.setEnabled.
void Ogre::GLESStateCacheManagerImp::setPolygonMode (GLenum mode) inline
See GLESStateCacheManager.setPolygonMode.
void Ogre::GLESStateCacheManagerImp::setPolygonMode (GLenum mode) inline
See GLESStateCacheManager.setPolygonMode.
void Ogre::GLESStateCacheManagerImp::setStencilMask (GLuint mask)
See GLESStateCacheManager.setStencilMask.
Referenced by getStencilMask().
void Ogre::GLESStateCacheManagerImp::setStencilMask (GLuint mask)
See GLESStateCacheManager.setStencilMask.
void Ogre::GLESStateCacheManagerImp::setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLESStateCacheManager.setTexParameteri.
void Ogre::GLESStateCacheManagerImp::setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLESStateCacheManager.setTexParameteri.
Member Data Documentation
GLBindingMap Ogre::GLESStateCacheManagerImp::mActiveBufferMap private
A map of different buffer types and the currently bound buffer for each type.
GLBindingMap Ogre::GLESStateCacheManagerImp::mActiveTextureMap private
A map of different texture types and the currently bound texture for each type.
unsigned char Ogre::GLESStateCacheManagerImp::mActiveTextureUnit private
Stores the currently active texture unit.
GLenum Ogre::GLESStateCacheManagerImp::mBlendEquation private
Stores the current blend equation.
Referenced by getBlendEquation().
GLenum Ogre::GLESStateCacheManagerImp::mBlendFuncDest private
GLenum Ogre::GLESStateCacheManagerImp::mBlendFuncSrc private
Stores the current blend function.
vector< GLclampf >::type Ogre::GLESStateCacheManagerImp::mClearColour private
Stores the current clear colour.
GLclampf Ogre::GLESStateCacheManagerImp::mClearDepth private
Stores the current depth clearing colour.
Referenced by getClearDepth().
vector< GLboolean >::type Ogre::GLESStateCacheManagerImp::mColourMask private
Stores the current colour write mask.
Referenced by getColourMask().
GLenum Ogre::GLESStateCacheManagerImp::mCullFace private
Stores the current face culling setting.
Referenced by getCullFace().
GLenum Ogre::GLESStateCacheManagerImp::mDepthFunc private
Stores the current depth test function.
Referenced by getDepthFunc().
GLboolean Ogre::GLESStateCacheManagerImp::mDepthMask private
Stores the current depth write mask.
Referenced by getDepthMask().
unsigned int Ogre::GLESStateCacheManagerImp::mDiscardBuffers private
Mask of buffers who contents can be discarded if GL_EXT_discard_framebuffer is supported.
Referenced by getDiscardBuffers().
vector<GLenum>::type Ogre::GLESStateCacheManagerImp::mEnableVector private
Array of each OpenGL feature that is enabled i.e. blending, depth test, etc.
GLuint Ogre::GLESStateCacheManagerImp::mLastBoundedTexID private
Stores the last bounded texture id.
GLenum Ogre::GLESStateCacheManagerImp::mPolygonMode private
Stores the current polygon rendering mode.
Referenced by getPolygonMode().
GLuint Ogre::GLESStateCacheManagerImp::mStencilMask private
Stores the current stencil mask.
Referenced by getStencilMask().
TexUnitsMap Ogre::GLESStateCacheManagerImp::mTexUnitsMap private
A map of texture parameters for each texture unit.
The documentation for this class was generated from the following files:
OgreGLESNullStateCacheManagerImp.h
OgreGLESStateCacheManagerImp.h