OGRE: Ogre::GLStateCacheManagerImp Class Reference
Ogre::GLStateCacheManagerImp Class Reference
An in memory cache of the OpenGL state.
#include <OgreGLStateCacheManagerImp.h>
Classes
struct TexGenParams
struct TextureUnitParams
Public Member Functions
GLStateCacheManagerImp (void)
GLStateCacheManagerImp (void)
~GLStateCacheManagerImp (void)
~GLStateCacheManagerImp (void)
bool activateGLTextureUnit (size_t unit)
See GLStateCacheManager.activateGLTextureUnit.
bool activateGLTextureUnit (size_t unit)
See GLStateCacheManager.activateGLTextureUnit.
void bindGLBuffer (GLenum target, GLuint buffer, bool force=false)
See GLStateCacheManager.bindGLBuffer.
void bindGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLStateCacheManager.bindGLBuffer.
void bindGLTexture (GLenum target, GLuint texture)
See GLStateCacheManager.bindGLTexture.
void bindGLTexture (GLenum target, GLuint texture)
See GLStateCacheManager.bindGLTexture.
void clearCache ()
See GLStateCacheManager.clearCache.
void clearCache ()
See GLStateCacheManager.clearCache.
void deleteGLBuffer (GLenum target, GLuint buffer, bool force=false)
See GLStateCacheManager.deleteGLBuffer.
void deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLStateCacheManager.deleteGLBuffer.
void disableTextureCoordGen (GLenum type)
Disable the specified texture coordinate generation option for the currently active texture unit.
void disableTextureCoordGen (GLenum type)
Disable the specified texture coordinate generation option for the currently active texture unit.
void enableTextureCoordGen (GLenum type)
Enable the specified texture coordinate generation option for the currently active texture unit.
void enableTextureCoordGen (GLenum type)
Enable the specified texture coordinate generation option for the currently active texture unit.
GLenum getBlendEquation (void) const
See GLStateCacheManager.getBlendEquation.
GLenum getBlendEquation (void) const
See GLStateCacheManager.getBlendEquation.
GLclampf getClearDepth (void) const
See GLStateCacheManager.getClearDepth.
GLclampf getClearDepth (void) const
See GLStateCacheManager.getClearDepth.
vector< GLboolean >::type & getColourMask (void)
See GLStateCacheManager.getColourMask.
vector< GLboolean >::type & getColourMask (void)
See GLStateCacheManager.getColourMask.
GLenum getCullFace (void) const
See GLStateCacheManager.getCullFace.
GLenum getCullFace (void) const
See GLStateCacheManager.getCullFace.
GLenum getDepthFunc (void) const
See GLStateCacheManager.getDepthFunc.
GLenum getDepthFunc (void) const
See GLStateCacheManager.getDepthFunc.
GLboolean getDepthMask (void) const
See GLStateCacheManager.getDepthMask.
GLboolean getDepthMask (void) const
See GLStateCacheManager.getDepthMask.
unsigned int getDiscardBuffers (void) const
See GLStateCacheManager.getDiscardBuffers.
unsigned int getDiscardBuffers (void) const
See GLStateCacheManager.getDiscardBuffers.
GLenum getPolygonMode (void) const
See GLStateCacheManager.getPolygonMode.
GLenum getPolygonMode (void) const
See GLStateCacheManager.getPolygonMode.
GLuint getStencilMask (void) const
See GLStateCacheManager.getStencilMask.
GLuint getStencilMask (void) const
See GLStateCacheManager.getStencilMask.
void getViewport (int *array)
Get viewport parameters.
void getViewport (int *array)
Get viewport parameters.
void initializeCache ()
See GLStateCacheManager.initializeCache.
void initializeCache ()
See GLStateCacheManager.initializeCache.
void invalidateStateForTexture (GLuint texture)
See GLStateCacheManager.invalidateStateForTexture.
void invalidateStateForTexture (GLuint texture)
See GLStateCacheManager.invalidateStateForTexture.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void setBlendEquation (GLenum eq)
See GLStateCacheManager.setBlendEquation.
void setBlendEquation (GLenum eqRGB, GLenum eqA)
Set the blend equation for RGB and alpha separately.
void setBlendEquation (GLenum eq)
See GLStateCacheManager.setBlendEquation.
void setBlendEquation (GLenum eqRGB, GLenum eqA)
Set the blend equation for RGB and alpha separately.
void setBlendFunc (GLenum source, GLenum dest)
See GLStateCacheManager.setBlendFunc.
void setBlendFunc (GLenum source, GLenum dest)
See GLStateCacheManager.setBlendFunc.
void setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLStateCacheManager.setClearColour.
void setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLStateCacheManager.setClearColour.
void setClearDepth (GLclampf depth)
See GLStateCacheManager.setClearDepth.
void setClearDepth (GLclampf depth)
See GLStateCacheManager.setClearDepth.
void setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLStateCacheManager.setColourMask.
void setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLStateCacheManager.setColourMask.
void setCullFace (GLenum face)
See GLStateCacheManager.setCullFace.
void setCullFace (GLenum face)
See GLStateCacheManager.setCullFace.
void setDepthFunc (GLenum func)
See GLStateCacheManager.setDepthFunc.
void setDepthFunc (GLenum func)
See GLStateCacheManager.setDepthFunc.
void setDepthMask (GLboolean mask)
See GLStateCacheManager.setDepthMask.
void setDepthMask (GLboolean mask)
See GLStateCacheManager.setDepthMask.
void setDiscardBuffers (unsigned int flags)
See GLStateCacheManager.setDiscardBuffers.
void setDiscardBuffers (unsigned int flags)
See GLStateCacheManager.setDiscardBuffers.
void setEnabled (GLenum flag, bool enabled)
See GLStateCacheManager.setEnabled.
void setEnabled (GLenum flag, bool enabled)
See GLStateCacheManager.setEnabled.
void setLightAmbient (GLfloat r, GLfloat g, GLfloat b)
See GLStateCacheManager.setLightAmbient.
void setLightAmbient (GLfloat r, GLfloat g, GLfloat b)
See GLStateCacheManager.setLightAmbient.
void setMaterialAmbient (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void setMaterialAmbient (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void setMaterialDiffuse (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void setMaterialDiffuse (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void setMaterialEmissive (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void setMaterialEmissive (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void setMaterialShininess (GLfloat shininess)
void setMaterialShininess (GLfloat shininess)
void setMaterialSpecular (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void setMaterialSpecular (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void setPointParameters (GLfloat *attenuation, float minSize, float maxSize)
void setPointParameters (GLfloat *attenuation, float minSize, float maxSize)
void setPointSize (GLfloat size)
void setPointSize (GLfloat size)
void setPolygonMode (GLenum mode)
See GLStateCacheManager.setPolygonMode.
void setPolygonMode (GLenum mode)
See GLStateCacheManager.setPolygonMode.
void setShadeModel (GLenum model)
See GLStateCacheManager.setShadeModel.
void setShadeModel (GLenum model)
See GLStateCacheManager.setShadeModel.
void setStencilMask (GLuint mask)
See GLStateCacheManager.setStencilMask.
void setStencilMask (GLuint mask)
See GLStateCacheManager.setStencilMask.
void setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLStateCacheManager.setTexParameteri.
void setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLStateCacheManager.setTexParameteri.
void setViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Set viewport parameters.
void setViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Set viewport parameters.
Private Types
typedef OGRE_HashMap< GLenum, GLuint > BindBufferMap
typedef OGRE_HashMap< GLenum, bool > GLbooleanStateMap
typedef OGRE_HashMap< GLenum, GLint > TexParameteriMap
typedef OGRE_HashMap< GLuint, TextureUnitParams > TexUnitsMap
Private Attributes
BindBufferMap mActiveBufferMap
A map of different buffer types and the currently bound buffer for each type.
size_t mActiveTextureUnit
Stores the currently active texture unit.
GLfloat mAmbient [4]
GLenum mBlendEquation
Stores the current blend equation.
GLenum mBlendEquationAlpha
GLenum mBlendEquationRGB
GLenum mBlendFuncDest
Stores the current blend destination function.
GLenum mBlendFuncSource
Stores the current blend source function.
GLbooleanStateMap mBoolStateMap
Array of each OpenGL feature that is enabled i.e. blending, depth test, etc.
OGRE_HashMap< GLenum, GLuint > mBoundTextures
Stores textures currently bound to each texture stage.
vector< GLclampf >::type mClearColour
Stores the current clear colour.
GLclampf mClearDepth
Stores the current depth clearing colour.
vector< GLboolean >::type mColourMask
Stores the current colour write mask.
GLenum mCullFace
Stores the current face culling setting.
GLenum mDepthFunc
Stores the current depth test function.
GLboolean mDepthMask
Stores the current depth write mask.
GLfloat mDiffuse [4]
unsigned int mDiscardBuffers
Mask of buffers who contents can be discarded if GL_EXT_discard_framebuffer is supported.
GLfloat mEmissive [4]
GLuint mLastBoundTexID
Stores the last bound texture id.
GLfloat mLightAmbient [4]
GLfloat mPointAttenuation [3]
GLfloat mPointSize
GLfloat mPointSizeMax
GLfloat mPointSizeMin
GLenum mPolygonMode
Stores the current polygon rendering mode.
GLenum mShadeModel
GLfloat mShininess
GLfloat mSpecular [4]
GLuint mStencilMask
Stores the current stencil mask.
OGRE_HashMap< GLenum, TexGenParams > mTextureCoordGen
Stores the currently enabled texcoord generation types per texture unit.
TexUnitsMap mTexUnitsMap
A map of texture parameters for each texture unit.
int mViewport [4]
Viewport origin and size.
Detailed Description
An in memory cache of the OpenGL state.
See also
GLStateCacheManager
Member Typedef Documentation
typedef OGRE_HashMap<GLenum, GLuint> Ogre::GLStateCacheManagerImp::BindBufferMap private
typedef OGRE_HashMap<GLenum, bool> Ogre::GLStateCacheManagerImp::GLbooleanStateMap private
typedef OGRE_HashMap<GLenum, GLint> Ogre::GLStateCacheManagerImp::TexParameteriMap private
typedef OGRE_HashMap<GLuint, TextureUnitParams> Ogre::GLStateCacheManagerImp::TexUnitsMap private
Constructor & Destructor Documentation
Ogre::GLStateCacheManagerImp::GLStateCacheManagerImp (void)
Ogre::GLStateCacheManagerImp::~GLStateCacheManagerImp (void)
Ogre::GLStateCacheManagerImp::GLStateCacheManagerImp (void)
Ogre::GLStateCacheManagerImp::~GLStateCacheManagerImp (void)
Member Function Documentation
bool Ogre::GLStateCacheManagerImp::activateGLTextureUnit (size_t unit)
See GLStateCacheManager.activateGLTextureUnit.
bool Ogre::GLStateCacheManagerImp::activateGLTextureUnit (size_t unit)
See GLStateCacheManager.activateGLTextureUnit.
void Ogre::GLStateCacheManagerImp::bindGLBuffer (GLenum target, GLuint buffer, bool force = false)
See GLStateCacheManager.bindGLBuffer.
void Ogre::GLStateCacheManagerImp::bindGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLStateCacheManager.bindGLBuffer.
void Ogre::GLStateCacheManagerImp::bindGLTexture (GLenum target, GLuint texture)
See GLStateCacheManager.bindGLTexture.
void Ogre::GLStateCacheManagerImp::bindGLTexture (GLenum target, GLuint texture)
See GLStateCacheManager.bindGLTexture.
void Ogre::GLStateCacheManagerImp::clearCache ()
See GLStateCacheManager.clearCache.
void Ogre::GLStateCacheManagerImp::clearCache ()
See GLStateCacheManager.clearCache.
void Ogre::GLStateCacheManagerImp::deleteGLBuffer (GLenum target, GLuint buffer, bool force = false)
See GLStateCacheManager.deleteGLBuffer.
void Ogre::GLStateCacheManagerImp::deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLStateCacheManager.deleteGLBuffer.
void Ogre::GLStateCacheManagerImp::disableTextureCoordGen (GLenum type)
Disable the specified texture coordinate generation option for the currently active texture unit.
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::disableTextureCoordGen (GLenum type)
Disable the specified texture coordinate generation option for the currently active texture unit.
void Ogre::GLStateCacheManagerImp::enableTextureCoordGen (GLenum type)
Enable the specified texture coordinate generation option for the currently active texture unit.
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::enableTextureCoordGen (GLenum type)
Enable the specified texture coordinate generation option for the currently active texture unit.
GLenum Ogre::GLStateCacheManagerImp::getBlendEquation (void) const inline
See GLStateCacheManager.getBlendEquation.
References mBlendEquation, setBlendEquation(), setBlendFunc(), setLightAmbient(), and setShadeModel().
GLenum Ogre::GLStateCacheManagerImp::getBlendEquation (void) const inline
See GLStateCacheManager.getBlendEquation.
GLclampf Ogre::GLStateCacheManagerImp::getClearDepth (void) const inline
See GLStateCacheManager.getClearDepth.
References mClearDepth, setClearColour(), and setClearDepth().
GLclampf Ogre::GLStateCacheManagerImp::getClearDepth (void) const inline
See GLStateCacheManager.getClearDepth.
vector<GLboolean>::type& Ogre::GLStateCacheManagerImp::getColourMask (void) inline
See GLStateCacheManager.getColourMask.
References mColourMask, and setColourMask().
vector<GLboolean>::type& Ogre::GLStateCacheManagerImp::getColourMask (void) inline
See GLStateCacheManager.getColourMask.
GLenum Ogre::GLStateCacheManagerImp::getCullFace (void) const inline
See GLStateCacheManager.getCullFace.
References disableTextureCoordGen(), enableTextureCoordGen(), getViewport(), mCullFace, setCullFace(), setMaterialAmbient(), setMaterialDiffuse(), setMaterialEmissive(), setMaterialShininess(), setMaterialSpecular(), setPointParameters(), setPointSize(), and setViewport().
GLenum Ogre::GLStateCacheManagerImp::getCullFace (void) const inline
See GLStateCacheManager.getCullFace.
GLenum Ogre::GLStateCacheManagerImp::getDepthFunc (void) const inline
See GLStateCacheManager.getDepthFunc.
References mDepthFunc, and setDepthFunc().
GLenum Ogre::GLStateCacheManagerImp::getDepthFunc (void) const inline
See GLStateCacheManager.getDepthFunc.
GLboolean Ogre::GLStateCacheManagerImp::getDepthMask (void) const inline
See GLStateCacheManager.getDepthMask.
References mDepthMask, and setDepthMask().
GLboolean Ogre::GLStateCacheManagerImp::getDepthMask (void) const inline
See GLStateCacheManager.getDepthMask.
unsigned int Ogre::GLStateCacheManagerImp::getDiscardBuffers (void) const inline
See GLStateCacheManager.getDiscardBuffers.
References mDiscardBuffers.
unsigned int Ogre::GLStateCacheManagerImp::getDiscardBuffers (void) const inline
See GLStateCacheManager.getDiscardBuffers.
GLenum Ogre::GLStateCacheManagerImp::getPolygonMode (void) const inline
See GLStateCacheManager.getPolygonMode.
References mPolygonMode, and setPolygonMode().
GLenum Ogre::GLStateCacheManagerImp::getPolygonMode (void) const inline
See GLStateCacheManager.getPolygonMode.
GLuint Ogre::GLStateCacheManagerImp::getStencilMask (void) const inline
See GLStateCacheManager.getStencilMask.
References mStencilMask, setEnabled(), and setStencilMask().
GLuint Ogre::GLStateCacheManagerImp::getStencilMask (void) const inline
See GLStateCacheManager.getStencilMask.
void Ogre::GLStateCacheManagerImp::getViewport (int * array)
Get viewport parameters.
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::getViewport (int * array)
Get viewport parameters.
void Ogre::GLStateCacheManagerImp::initializeCache ()
See GLStateCacheManager.initializeCache.
void Ogre::GLStateCacheManagerImp::initializeCache ()
See GLStateCacheManager.initializeCache.
void Ogre::GLStateCacheManagerImp::invalidateStateForTexture (GLuint texture)
See GLStateCacheManager.invalidateStateForTexture.
void Ogre::GLStateCacheManagerImp::invalidateStateForTexture (GLuint texture)
See GLStateCacheManager.invalidateStateForTexture.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
void Ogre::GLStateCacheManagerImp::setBlendEquation (GLenum eq)
See GLStateCacheManager.setBlendEquation.
Referenced by getBlendEquation().
void Ogre::GLStateCacheManagerImp::setBlendEquation (GLenum eqRGB, GLenum eqA)
Set the blend equation for RGB and alpha separately.
void Ogre::GLStateCacheManagerImp::setBlendEquation (GLenum eq)
See GLStateCacheManager.setBlendEquation.
void Ogre::GLStateCacheManagerImp::setBlendEquation (GLenum eqRGB, GLenum eqA)
Set the blend equation for RGB and alpha separately.
void Ogre::GLStateCacheManagerImp::setBlendFunc (GLenum source, GLenum dest)
See GLStateCacheManager.setBlendFunc.
Referenced by getBlendEquation().
void Ogre::GLStateCacheManagerImp::setBlendFunc (GLenum source, GLenum dest)
See GLStateCacheManager.setBlendFunc.
void Ogre::GLStateCacheManagerImp::setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLStateCacheManager.setClearColour.
Referenced by getClearDepth().
void Ogre::GLStateCacheManagerImp::setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLStateCacheManager.setClearColour.
void Ogre::GLStateCacheManagerImp::setClearDepth (GLclampf depth)
See GLStateCacheManager.setClearDepth.
Referenced by getClearDepth().
void Ogre::GLStateCacheManagerImp::setClearDepth (GLclampf depth)
See GLStateCacheManager.setClearDepth.
void Ogre::GLStateCacheManagerImp::setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLStateCacheManager.setColourMask.
Referenced by getColourMask().
void Ogre::GLStateCacheManagerImp::setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLStateCacheManager.setColourMask.
void Ogre::GLStateCacheManagerImp::setCullFace (GLenum face)
See GLStateCacheManager.setCullFace.
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::setCullFace (GLenum face)
See GLStateCacheManager.setCullFace.
void Ogre::GLStateCacheManagerImp::setDepthFunc (GLenum func)
See GLStateCacheManager.setDepthFunc.
Referenced by getDepthFunc().
void Ogre::GLStateCacheManagerImp::setDepthFunc (GLenum func)
See GLStateCacheManager.setDepthFunc.
void Ogre::GLStateCacheManagerImp::setDepthMask (GLboolean mask)
See GLStateCacheManager.setDepthMask.
Referenced by getDepthMask().
void Ogre::GLStateCacheManagerImp::setDepthMask (GLboolean mask)
See GLStateCacheManager.setDepthMask.
void Ogre::GLStateCacheManagerImp::setDiscardBuffers (unsigned int flags) inline
See GLStateCacheManager.setDiscardBuffers.
void Ogre::GLStateCacheManagerImp::setDiscardBuffers (unsigned int flags) inline
See GLStateCacheManager.setDiscardBuffers.
void Ogre::GLStateCacheManagerImp::setEnabled (GLenum flag, bool enabled)
See GLStateCacheManager.setEnabled.
Referenced by getStencilMask().
void Ogre::GLStateCacheManagerImp::setEnabled (GLenum flag, bool enabled)
See GLStateCacheManager.setEnabled.
void Ogre::GLStateCacheManagerImp::setLightAmbient (GLfloat r, GLfloat g, GLfloat b)
See GLStateCacheManager.setLightAmbient.
Referenced by getBlendEquation().
void Ogre::GLStateCacheManagerImp::setLightAmbient (GLfloat r, GLfloat g, GLfloat b)
See GLStateCacheManager.setLightAmbient.
void Ogre::GLStateCacheManagerImp::setMaterialAmbient (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::setMaterialAmbient (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void Ogre::GLStateCacheManagerImp::setMaterialDiffuse (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::setMaterialDiffuse (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void Ogre::GLStateCacheManagerImp::setMaterialEmissive (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::setMaterialEmissive (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void Ogre::GLStateCacheManagerImp::setMaterialShininess (GLfloat shininess)
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::setMaterialShininess (GLfloat shininess)
void Ogre::GLStateCacheManagerImp::setMaterialSpecular (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::setMaterialSpecular (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void Ogre::GLStateCacheManagerImp::setPointParameters (GLfloat * attenuation, float minSize, float maxSize)
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::setPointParameters (GLfloat * attenuation, float minSize, float maxSize)
void Ogre::GLStateCacheManagerImp::setPointSize (GLfloat size)
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::setPointSize (GLfloat size)
void Ogre::GLStateCacheManagerImp::setPolygonMode (GLenum mode)
See GLStateCacheManager.setPolygonMode.
Referenced by getPolygonMode().
void Ogre::GLStateCacheManagerImp::setPolygonMode (GLenum mode)
See GLStateCacheManager.setPolygonMode.
void Ogre::GLStateCacheManagerImp::setShadeModel (GLenum model)
See GLStateCacheManager.setShadeModel.
Referenced by getBlendEquation().
void Ogre::GLStateCacheManagerImp::setShadeModel (GLenum model)
See GLStateCacheManager.setShadeModel.
void Ogre::GLStateCacheManagerImp::setStencilMask (GLuint mask)
See GLStateCacheManager.setStencilMask.
Referenced by getStencilMask().
void Ogre::GLStateCacheManagerImp::setStencilMask (GLuint mask)
See GLStateCacheManager.setStencilMask.
void Ogre::GLStateCacheManagerImp::setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLStateCacheManager.setTexParameteri.
void Ogre::GLStateCacheManagerImp::setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLStateCacheManager.setTexParameteri.
void Ogre::GLStateCacheManagerImp::setViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Set viewport parameters.
Referenced by getCullFace().
void Ogre::GLStateCacheManagerImp::setViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Set viewport parameters.
Member Data Documentation
BindBufferMap Ogre::GLStateCacheManagerImp::mActiveBufferMap private
A map of different buffer types and the currently bound buffer for each type.
size_t Ogre::GLStateCacheManagerImp::mActiveTextureUnit private
Stores the currently active texture unit.
GLfloat Ogre::GLStateCacheManagerImp::mAmbient private
GLenum Ogre::GLStateCacheManagerImp::mBlendEquation private
Stores the current blend equation.
Referenced by getBlendEquation().
GLenum Ogre::GLStateCacheManagerImp::mBlendEquationAlpha private
GLenum Ogre::GLStateCacheManagerImp::mBlendEquationRGB private
GLenum Ogre::GLStateCacheManagerImp::mBlendFuncDest private
Stores the current blend destination function.
GLenum Ogre::GLStateCacheManagerImp::mBlendFuncSource private
Stores the current blend source function.
GLbooleanStateMap Ogre::GLStateCacheManagerImp::mBoolStateMap private
Array of each OpenGL feature that is enabled i.e. blending, depth test, etc.
OGRE_HashMap<GLenum, GLuint> Ogre::GLStateCacheManagerImp::mBoundTextures private
Stores textures currently bound to each texture stage.
vector< GLclampf >::type Ogre::GLStateCacheManagerImp::mClearColour private
Stores the current clear colour.
GLclampf Ogre::GLStateCacheManagerImp::mClearDepth private
Stores the current depth clearing colour.
Referenced by getClearDepth().
vector< GLboolean >::type Ogre::GLStateCacheManagerImp::mColourMask private
Stores the current colour write mask.
Referenced by getColourMask().
GLenum Ogre::GLStateCacheManagerImp::mCullFace private
Stores the current face culling setting.
Referenced by getCullFace().
GLenum Ogre::GLStateCacheManagerImp::mDepthFunc private
Stores the current depth test function.
Referenced by getDepthFunc().
GLboolean Ogre::GLStateCacheManagerImp::mDepthMask private
Stores the current depth write mask.
Referenced by getDepthMask().
GLfloat Ogre::GLStateCacheManagerImp::mDiffuse private
unsigned int Ogre::GLStateCacheManagerImp::mDiscardBuffers private
Mask of buffers who contents can be discarded if GL_EXT_discard_framebuffer is supported.
Referenced by getDiscardBuffers().
GLfloat Ogre::GLStateCacheManagerImp::mEmissive private
GLuint Ogre::GLStateCacheManagerImp::mLastBoundTexID private
Stores the last bound texture id.
GLfloat Ogre::GLStateCacheManagerImp::mLightAmbient private
GLfloat Ogre::GLStateCacheManagerImp::mPointAttenuation private
GLfloat Ogre::GLStateCacheManagerImp::mPointSize private
GLfloat Ogre::GLStateCacheManagerImp::mPointSizeMax private
GLfloat Ogre::GLStateCacheManagerImp::mPointSizeMin private
GLenum Ogre::GLStateCacheManagerImp::mPolygonMode private
Stores the current polygon rendering mode.
Referenced by getPolygonMode().
GLenum Ogre::GLStateCacheManagerImp::mShadeModel private
GLfloat Ogre::GLStateCacheManagerImp::mShininess private
GLfloat Ogre::GLStateCacheManagerImp::mSpecular private
GLuint Ogre::GLStateCacheManagerImp::mStencilMask private
Stores the current stencil mask.
Referenced by getStencilMask().
OGRE_HashMap<GLenum, TexGenParams> Ogre::GLStateCacheManagerImp::mTextureCoordGen private
Stores the currently enabled texcoord generation types per texture unit.
TexUnitsMap Ogre::GLStateCacheManagerImp::mTexUnitsMap private
A map of texture parameters for each texture unit.
int Ogre::GLStateCacheManagerImp::mViewport private
Viewport origin and size.
The documentation for this class was generated from the following files:
OgreGLNullStateCacheManagerImp.h
OgreGLStateCacheManagerImp.h