OGRE: Ogre::GLSL::CPreprocessor::Token Class Reference
Ogre::GLSL::CPreprocessor::Token Class Reference
A input token.
Public Types
enum Kind {
TK_EOS, TK_ERROR, TK_WHITESPACE, TK_NEWLINE,
TK_LINECONT, TK_NUMBER, TK_KEYWORD, TK_PUNCTUATION,
TK_DIRECTIVE, TK_STRING, TK_COMMENT, TK_LINECOMMENT,
TK_TEXT
}
Public Member Functions
Token ()
Token (Kind iType)
Token (Kind iType, const char *iString, size_t iLength)
Token (const Token &iOther)
~Token ()
void Append (const char *iString, size_t iLength)
Append a string to this token.
void Append (const Token &iOther)
Append a token to this token.
void AppendNL (int iCount)
Append given number of newlines to this token.
int CountNL ()
Count number of newlines in this token.
bool GetValue (long &oValue) const
Get the numeric value of the token.
Token & operator= (const Token &iOther)
Assignment operator.
bool operator== (const Token &iOther)
Test two tokens for equality.
void SetValue (long iValue)
Set the numeric value of the token.
Public Attributes
union {
char * Buffer
A memory-allocated string.
const char * String
A pointer somewhere into the input buffer.
};
size_t Allocated
True if string was allocated (and must be freed)
size_t Length
Token length in bytes.
Kind Type
Token type.
Detailed Description
A input token.
For performance reasons most tokens will point to portions of the input stream, so no unneeded memory allocation is done. However, in some cases we must allocate different memory for token storage, in this case this is signalled by setting the Allocated member to non-zero in which case the destructor will know that it must free memory on object destruction.
Again for performance reasons we use malloc/realloc/free here because C++-style new[] lacks the realloc() counterpart.
Member Enumeration Documentation
enum Ogre::GLSL::CPreprocessor::Token::Kind
Enumerator
TK_EOS
TK_ERROR
TK_WHITESPACE
TK_NEWLINE
TK_LINECONT
TK_NUMBER
TK_KEYWORD
TK_PUNCTUATION
TK_DIRECTIVE
TK_STRING
TK_COMMENT
TK_LINECOMMENT
TK_TEXT
Constructor & Destructor Documentation
Ogre::GLSL::CPreprocessor::Token::Token () inline
Ogre::GLSL::CPreprocessor::Token::Token (Kind iType) inline
Ogre::GLSL::CPreprocessor::Token::Token (Kind iType, const char * iString, size_t iLength) inline
Ogre::GLSL::CPreprocessor::Token::Token (const Token & iOther) inline
References Allocated, Length, String, and Type.
Ogre::GLSL::CPreprocessor::Token::~Token () inline
References Buffer.
Member Function Documentation
void Ogre::GLSL::CPreprocessor::Token::Append (const char * iString, size_t iLength)
Append a string to this token.
Referenced by operator=().
void Ogre::GLSL::CPreprocessor::Token::Append (const Token & iOther)
Append a token to this token.
void Ogre::GLSL::CPreprocessor::Token::AppendNL (int iCount)
Append given number of newlines to this token.
Referenced by operator=().
int Ogre::GLSL::CPreprocessor::Token::CountNL ()
Count number of newlines in this token.
Referenced by operator=().
bool Ogre::GLSL::CPreprocessor::Token::GetValue (long & oValue) const
Get the numeric value of the token.
Referenced by operator=().
Token& Ogre::GLSL::CPreprocessor::Token::operator= (const Token & iOther) inline
Assignment operator.
References Allocated, Append(), AppendNL(), Buffer, CountNL(), GetValue(), Length, SetValue(), String, and Type.
bool Ogre::GLSL::CPreprocessor::Token::operator== (const Token & iOther) inline
Test two tokens for equality.
References Length, and String.
void Ogre::GLSL::CPreprocessor::Token::SetValue (long iValue)
Set the numeric value of the token.
Referenced by operator=().
Member Data Documentation
union { ... }
size_t Ogre::GLSL::CPreprocessor::Token::Allocated mutable
True if string was allocated (and must be freed)
Referenced by operator=(), and Token().
char* Ogre::GLSL::CPreprocessor::Token::Buffer
A memory-allocated string.
Referenced by operator=(), and ~Token().
size_t Ogre::GLSL::CPreprocessor::Token::Length
Token length in bytes.
Referenced by operator=(), operator==(), and Token().
const char* Ogre::GLSL::CPreprocessor::Token::String
A pointer somewhere into the input buffer.
Referenced by operator=(), operator==(), and Token().
Kind Ogre::GLSL::CPreprocessor::Token::Type
Token type.
Referenced by operator=(), and Token().
The documentation for this class was generated from the following file:
src/GLSL/include/OgreGLSLPreprocessor.h